[build]
  command = "npm run build"
  publish = "dist/shop-co/browser"
  functions = "functions"

[dev]
  command = "ng serve"
  port = 4300
  functionPort = 3000
  publish = "dist/shop-co/browser"

[[redirects]]
  from = "/*"
  to = "/index.csr.html"
  status = 200

[[plugins]]
  package = "@netlify/angular-runtime@latest"