[build]
  publish = "dist/shop-co/browser"
  command = "npm run build"

[dev]
  command = "npm run dev"
  port = 3000
  targetPort = 3000

[[plugins]]
  package = "@netlify/angular-runtime"

[[redirects]]
  from = "/*"
  to = "/index.csr.html"
  status = 200
