[build]
  command = "npm run build"
  functions = "./functions"
  publish = "dist/shop-co/browser"

[dev]
  command = "npm run start"
  functions = "./functions"
  publish = "src"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
  package = "@netlify/plugin-angular-universal"